/*
virtual_key_show(l)
virtual_key_show(esq)
virtual_key_show(dire)
virtual_key_show(das)
virtual_key_show(atk)
virtual_key_show(b)
virtual_key_show(lw)
virtual_key_show(sqs)
virtual_key_show(cd)
virtual_key_show(db)
*/
